"""add asset_outputs table

Revision ID: 0a9099bb02a1
Revises: 2f6a3d9b7c10
Create Date: 2026-06-02 23:04:30.925578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a9099bb02a1'
down_revision: Union[str, Sequence[str], None] = '2f6a3d9b7c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_outputs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('output_type', sa.String(), nullable=False),
    sa.Column('output_content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('fk_content_chunks_worker_result_id_worker_results'), 'content_chunks', type_='foreignkey')
    op.drop_column('content_chunks', 'worker_result_id')
    op.drop_table('worker_results')
    op.alter_column('content_chunks', 'extracted_content_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_chunks', sa.Column('worker_result_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_content_chunks_worker_result_id_worker_results'), 'content_chunks', 'worker_results', ['worker_result_id'], ['id'])
    op.alter_column('content_chunks', 'extracted_content_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('worker_results',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('worker_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('worker_results_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('worker_results_pkey'))
    )
    op.drop_table('asset_outputs')
    # ### end Alembic commands ###
