"""Initial migration

Revision ID: 557bbd1b471b
Revises: 
Create Date: 2026-05-27 18:45:34.905168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557bbd1b471b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    # op.execute("CREATE TYPE processingstatus AS ENUM ('PENDING', 'PROCESSING', 'READY', 'FAILED')")
    
    op.create_table('extracted_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # # Map old values to new enum values
    # op.execute("UPDATE assets SET processing_status = 'PENDING' WHERE processing_status = 'uploaded'")
    # op.execute("UPDATE assets SET processing_status = 'PENDING' WHERE processing_status NOT IN ('PENDING', 'PROCESSING', 'READY', 'FAILED')")
    
    # # Cast the column properly with USING clause
    # op.execute('ALTER TABLE assets ALTER COLUMN processing_status TYPE processingstatus USING processing_status::processingstatus')
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'processing_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='processingstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('extracted_content')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS processingstatus")
    # ### end Alembic commands ###
